In [0]:
emp_schema = ["Employee_ID", "Name", "DOJ", "Dept_Id", "Gender", "salary"]

emp_data = [(10, "raj Kumar", "1999","100", "M", 2000),
            (20, "Ravi Kumar", "2002","200", "M", 3000),
            (30, "Arjun Kumar", "2004","400", "M", 25000),
            (40, "Rani Kumari", "2006","100", "F", 20000),
            (50, "Rekha", "2008","300", None , 9000),
            (60, "raj Kumar", "2010",None, None, 2000)
            ]

df_emp = spark.createDataFrame(data= emp_data, schema= emp_schema)

display(df_emp)

Employee_ID,Name,DOJ,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000

In [0]:
from pyspark.sql.functions import lit

In [0]:
emp_addcolumn = df_emp.withColumn("Location", lit("Mumbai")).show()

+-----------+-----------+----+-------+------+------+--------+
|Employee_ID|       Name| DOJ|Dept_Id|Gender|salary|Location|
+-----------+-----------+----+-------+------+------+--------+
|         10|  raj Kumar|1999|    100|     M|  2000|  Mumbai|
|         20| Ravi Kumar|2002|    200|     M|  3000|  Mumbai|
|         30|Arjun Kumar|2004|    400|     M| 25000|  Mumbai|
|         40|Rani Kumari|2006|    100|     F| 20000|  Mumbai|
|         50|      Rekha|2008|    300|  null|  9000|  Mumbai|
|         60|  raj Kumar|2010|   null|  null|  2000|  Mumbai|
+-----------+-----------+----+-------+------+------+--------+

In [0]:
emp_addcolumn = df_emp.withColumn("Location", lit("Mumbai"))

display(emp_addcolumn)

Employee_ID,Name,DOJ,Dept_Id,Gender,salary,Location
10,raj Kumar,1999,100,M,2000,Mumbai
20,Ravi Kumar,2002,200,M,3000,Mumbai
30,Arjun Kumar,2004,400,M,25000,Mumbai
40,Rani Kumari,2006,100,F,20000,Mumbai
50,Rekha,2008,300,null,9000,Mumbai
60,raj Kumar,2010,null,null,2000,Mumbai

In [0]:
df_emp_addcolumn1 = df_emp.withColumn("Bonus", df_emp.salary*.10)

type(df_emp)
display(df_emp_addcolumn1)

Employee_ID,Name,DOJ,Dept_Id,Gender,salary,Bonus
10,raj Kumar,1999,100,M,2000,200.0
20,Ravi Kumar,2002,200,M,3000,300.0
30,Arjun Kumar,2004,400,M,25000,2500.0
40,Rani Kumari,2006,100,F,20000,2000.0
50,Rekha,2008,300,null,9000,900.0
60,raj Kumar,2010,null,null,2000,200.0

In [0]:
from pyspark.sql.functions import concat

In [0]:
display(df_emp)

df_emp_addcolumn2 = df_emp.withColumn("Bonus", df_emp.salary*.10).withColumn("New Dept_Id", concat("Employee_ID", lit("_"), "Dept_Id")) #concat(lit("1 "), "Dept_Id" # lit("1 "),

df_emp_addcolumn2.show()

Employee_ID,Name,DOJ,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000

+-----------+-----------+----+-------+------+------+------+-----------+
|Employee_ID|       Name| DOJ|Dept_Id|Gender|salary| Bonus|New Dept_Id|
+-----------+-----------+----+-------+------+------+------+-----------+
|         10|  raj Kumar|1999|    100|     M|  2000| 200.0|     10_100|
|         20| Ravi Kumar|2002|    200|     M|  3000| 300.0|     20_200|
|         30|Arjun Kumar|2004|    400|     M| 25000|2500.0|     30_400|
|         40|Rani Kumari|2006|    100|     F| 20000|2000.0|     40_100|
|         50|      Rekha|2008|    300|  null|  9000| 900.0|     50_300|
|         60|  raj Kumar|2010|   null|  null|  2000| 200.0|       null|
+-----------+-----------+----+-------+------+------+------+-----------+

In [0]:
df_emp_renameColmn = df_emp.withColumnRenamed("Name", "Full Name")

df_emp_renameColmn.show()

+-----------+-----------+----+-------+------+------+
|Employee_ID|  Full Name| DOJ|Dept_Id|Gender|salary|
+-----------+-----------+----+-------+------+------+
|         10|  raj Kumar|1999|    100|     M|  2000|
|         20| Ravi Kumar|2002|    200|     M|  3000|
|         30|Arjun Kumar|2004|    400|     M| 25000|
|         40|Rani Kumari|2006|    100|     F| 20000|
|         50|      Rekha|2008|    300|  null|  9000|
|         60|  raj Kumar|2010|   null|  null|  2000|
+-----------+-----------+----+-------+------+------+

In [0]:
df_emp_renameColmn = df_emp.withColumnRenamed("Name", "Full Name").withColumnRenamed("DOJ", "Year of Joining")
display(df_emp_renameColmn)

Employee_ID,Full Name,Year of Joining,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000

In [0]:
df_emp_renameColmn.drop("New Dept_Id")

display(df_emp_renameColmn)

Employee_ID,Full Name,Year of Joining,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000

In [0]:
display(df_emp_renameColmn)

df_emp_renameColmn.drop("New Dept_Id").drop("Gender")

display(df_emp_renameColmn)

Employee_ID,Full Name,Year of Joining,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000

Employee_ID,Full Name,Year of Joining,Dept_Id,Gender,salary
10,raj Kumar,1999,100,M,2000
20,Ravi Kumar,2002,200,M,3000
30,Arjun Kumar,2004,400,M,25000
40,Rani Kumari,2006,100,F,20000
50,Rekha,2008,300,null,9000
60,raj Kumar,2010,null,null,2000