In [0]:
emp_schema = ["Employee_ID", "Name", "DOJ", "Dept_Id", "Gender", "salary"]

emp_data = [(10, "raj Kumar", "1999-01-01","100", "M", 2000),
            (20, "Ravi Kumar", "2002-02-02","200", "M", 3000),
            (30, "Arjun Kumar", "2004-03-03","400", "M", 25000),
            (40, "Rani Kumari", "2006-04-04","100", "F", 20000),
            (50, "Rekha", "2008-05-18","300", None , 9000),
            (60, "raj Kumar B", None,None, None, 2000),
            (None,None, None, None,None, None)
            ]

df_emp = spark.createDataFrame(data= emp_data, schema= emp_schema)

display(df_emp)

Employee_ID,Name,DOJ,Dept_Id,Gender,salary
10,raj Kumar,1999-01-01,100,M,2000
20,Ravi Kumar,2002-02-02,200,M,3000
30,Arjun Kumar,2004-03-03,400,M,25000
40,Rani Kumari,2006-04-04,100,F,20000
50,Rekha,2008-05-18,300,null,9000
60,raj Kumar B,null,null,null,2000
null,null,null,null,null,null

In [0]:
#Reading single File
df_s = spark.read.format("csv").option("inferSchema", True).option("header", True).option("sep",",").load("/FileStore/tables/emp_details.csv")

display (df_s)

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
null,null,null,null,null
90,klmo,xyz,7,70000

In [0]:
display (df_s.na.drop())

display (df_s.dropna())

display (df_s.dropna("any"))

display (df_s.dropna("all"))

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
90,klmo,xyz,7,70000

In [0]:
display(df_emp)

display (df_emp.dropna("all"))

Employee_ID,Name,DOJ,Dept_Id,Gender,salary
10,raj Kumar,1999-01-01,100,M,2000
20,Ravi Kumar,2002-02-02,200,M,3000
30,Arjun Kumar,2004-03-03,400,M,25000
40,Rani Kumari,2006-04-04,100,F,20000
50,Rekha,2008-05-18,300,null,9000
60,raj Kumar B,null,null,null,2000
null,null,null,null,null,null

Employee_ID,Name,DOJ,Dept_Id,Gender,salary
10,raj Kumar,1999-01-01,100,M,2000
20,Ravi Kumar,2002-02-02,200,M,3000
30,Arjun Kumar,2004-03-03,400,M,25000
40,Rani Kumari,2006-04-04,100,F,20000
50,Rekha,2008-05-18,300,null,9000
60,raj Kumar B,null,null,null,2000

In [0]:
display(df_s)

display(df_s.dropna(subset= ["Experience", "Salary"]))

display(df_s.na.drop(subset= ["Experience", "Salary"]))

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
null,null,null,null,null
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
90,klmo,xyz,7,70000

In [0]:
df_s.printSchema()

display(df_s.na.fill(value= 0))  # if value is integer it replace only integer columns and if value is string it replace only string columns.

display(df_s.fillna(value=0))

display(df_s.fillna(value="NA"))

root
 |-- Employee_id: integer (nullable = true)
 |-- Emp_First_name: string (nullable = true)
 |-- Emp_Last_Same: string (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,0
0,F_name,L_Name,0,8000
0,null,null,0,0
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,0
0,F_name,L_Name,0,8000
0,null,null,0,0
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,NA,2,null
null,F_name,L_Name,null,8000
null,NA,NA,null,null
90,klmo,xyz,7,70000

In [0]:
display(df_s)

display(df_s.fillna(value=0, subset=["Experience"]))

display(df_s.na.fill(value='XXX', subset=["Emp_First_name"]))

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
null,null,null,null,null
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,0,8000
null,null,null,0,null
90,klmo,xyz,7,70000

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
null,XXX,null,null,null
90,klmo,xyz,7,70000

In [0]:
display(df_s)

df_s.printSchema()

display(df_s.fillna({"Employee_id": 0, "Emp_First_name": 'Missing First name', "Emp_Last_Same":'Missing Last Name', "Experience": '0', "Salary": 0}))

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,null,2,null
null,F_name,L_Name,null,8000
null,null,null,null,null
90,klmo,xyz,7,70000

root
 |-- Employee_id: integer (nullable = true)
 |-- Emp_First_name: string (nullable = true)
 |-- Emp_Last_Same: string (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Monali,S.,9,60000
20,Harshad,K,2,25000
30,ABC,XYZ,3,30000
40,AAA,BBB,5,40000
50,XXX,XYZ,8,50000
60,abc,Missing Last Name,2,0
0,F_name,L_Name,0,8000
0,Missing First name,Missing Last Name,0,0
90,klmo,xyz,7,70000